### ISSUE TITLE
Package file not up-to-date on http://exopenwrt.rlnd.black/barrier_breaker/14.07/ar71xx/packages/exopenwrt/

### ISSUE THREAD

**Issue by MangeshBhamre** [black-roland/exOpenWrt#14]
If I try to build openwrt OS image with dnscrypt-proxy package pointing repository to 14.07 it does not build.  Package file hash and version in "Packages" file is different than the files stored in below folder. Please correct asap.

http://exopenwrt.rlnd.black/barrier_breaker/14.07/ar71xx/packages/exopenwrt/

File name in "Packages" is Filename: dnscrypt-proxy-resolvers_1.6.0-4.E_ar71xx.ipk
Where as in folder its dnscrypt-proxy-resolvers_1.6.0-5.E_ar71xx.ipk   (New version).

**Comment by black-roland** [comment]
Ooops, fixed.

Thank you for the report.
