### ISSUE TITLE
Huge performerce issues 

### ISSUE THREAD

**Issue by Misiek304** [black-roland/exOpenWrt#15]
With the newest version (1.6.0) on Barrier Breaker on TP-LINK WR1043ND v1 I have huge system load which makes my internet not working at all. This all happens for example with uTorrent and approximately 4-6 thousands of connections and speed 5MB/s and more. This kind of problems are no present with version 1.4.3. With 1.6.0 my CPU usage is around 70-80% and DNS are not responding at all. I can't view any websites.

**Comment by black-roland** [comment]
I does not have router with Barrier Breaker. Can you test using Chaos Calmer?

**Comment by Misiek304** [comment]
I already fixed that. Turns out it changing "ephemeral_keys" to "1" is causing the problem. There should be a note that enabling this feature can cause serious performance issues.

**Comment by black-roland** [comment]
Thank you for report. Added note to config and readme.
