### ISSUE TITLE
Can't load library 'libsodium.so.17'

### ISSUE THREAD

**Issue by dartraiden** [black-roland/exOpenWrt#16]
11 Dec after the 37d160a908af5dead8c92bce953d7b41e55b1771 I performed as usual

```
opkg update
opkg list-upgradable
```

This commands showed that the updates are available for libsodium and dnscrypt-proxy-resolvers. So I execute

```
opkg update libsodium
opkg update dnscrypt-proxy-resolvers
```

12 Dec I restarted the router and DNSCrypt does not start. There was no record of it in the system log.
/usr/sbin/dnscrypt-proxy tell me "can't load library 'libsodium.so.17'" (but has been installed libsodium.so.18).
I used the DNS 8.8.8.8 on PC, go to [repo](http://exopenwrt.roland.black/chaos_calmer/15.05/ar71xx/packages/exopenwrt/) and check the versions of the packages with "System → Software". They matched. In any case, I manually downloaded and reinstalled dnscrypt-proxy package and it now works.

Perhaps you forgot bamp package version?

**Comment by black-roland** [comment]
Thanks for the report. Version just updated.

> Perhaps you forgot bamp package version?
Yes :( I did a full reinstallation on my router and not encountered problems.
