### ISSUE TITLE
Can't works,how to debug

### ISSUE THREAD

**Issue by FreeVicto** [black-roland/exOpenWrt#17]
i have install the latest ipk on openwrt(Barrier Breaker) and it start fine, i config it as https://wiki.openwrt.org/inbox/dnscrypt indicate, but it can't works, how to find the problem, how to debug it?

**Comment by black-roland** [comment]
You can view logs by logread:
```
$ /etc/init.d/dnscrypt-proxy start
$ logread -e dnscrypt-proxy
```

Also try to ping remote DNS server. IP address can be found in `/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv`:
```
$ cat /usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv | grep fvz-anyone | cut -d ',' -f 11 
185.121.177.177
$ ping -c 1 185.121.177.177
```

**Comment by FreeVicto** [comment]
@black-roland 
Hi Thank you,, it's fine now, this issue can be closed.
