### ISSUE TITLE
libsodium depends on libpthread

### ISSUE THREAD

**Issue by pupie** [black-roland/exOpenWrt#18]
Hi, 
   I just updated your feeds and tried compile dnscrypt-proxy for openwrt cc and encountered following error. It seems that you bumped version and new dependency is needed.
I did not get this error on dnscrypt 1.6.x

`make[3]: Entering directory '/home/colin/openwrt/feeds/dnscrypt/package/libsodium'
mkdir -p /home/colin/openwrt/bin/ar71xx/packages /home/colin/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/libsodium-1.0.11/ipkg-ar71xx/libsodium/CONTROL /home/colin/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/pkginfo
install -d -m0755 /home/colin/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/libsodium-1.0.11/ipkg-ar71xx/libsodium/usr/lib
cp -fpR /home/colin/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/libsodium-1.0.11/ipkg-install/usr/lib/libsodium.so* /home/colin/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/libsodium-1.0.11/ipkg-ar71xx/libsodium/usr/lib/
find /home/colin/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/libsodium-1.0.11/ipkg-ar71xx/libsodium -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package libsodium is missing dependencies for the following libraries:
libpthread.so.0
Makefile:55: recipe for target '/home/colin/openwrt/bin/ar71xx/packages/dnscrypt/libsodium_1.0.11-1.E_ar71xx.ipk' failed
make[3]: *** [/home/colin/openwrt/bin/ar71xx/packages/dnscrypt/libsodium_1.0.11-1.E_ar71xx.ipk] Error 1
make[3]: Leaving directory '/home/colin/openwrt/feeds/dnscrypt/package/libsodium'
package/Makefile:191: recipe for target 'package/feeds/dnscrypt/libsodium/compile' failed
make[2]: *** [package/feeds/dnscrypt/libsodium/compile] Error 2
make[2]: Leaving directory '/home/colin/openwrt'
package/Makefile:188: recipe for target '/home/colin/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: *** [/home/colin/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/colin/openwrt'
/home/colin/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2
`

After adding following line to Makefile for libsodium and error is gone.
` DEPENDS:=+libpthread
`

**Comment by black-roland** [comment]
Hi. Use [chaos-calmer](https://github.com/black-roland/exOpenWrt/tree/chaos-calmer) branch.

It is problem with uClibc. OpenWrt CC uses uClibc, although development OpenWrt version (trunk) uses Musl. Some pthread methods not implemented in uClibc. Libsodium has [`--without-pthreads`](https://github.com/black-roland/exOpenWrt/blob/chaos-calmer/package/libsodium/Makefile#L43) flag in this case.

**Comment by black-roland** [comment]
Also see `src-git packages https://github.com/reponame/packages.git;special_branch` feeds example: https://wiki.openwrt.org/doc/devel/feeds#feed_configuration

**Comment by pupie** [comment]
Hi, 
thanks, I confirm that this problem is gone with chaos-calmer branch of your repository.
Have a nice day.
