### ISSUE TITLE
能提供 在openwrt 下 的 dnscrypt-proxy 的 luci(Can provide at openwrt of dnscrypt-proxy was luci)

### ISSUE THREAD

**Issue by q158073378252010** [black-roland/exOpenWrt#19]

**Comment by black-roland** [comment]
You mean what you want Luci interface for dnscrypt-proxy?

Sorry, but it is not primary goal. I don't use Luci and can't test Luci properly.

Pull requests are welcome.

**Comment by q158073378252010** [comment]
You can talk about how to write dnscrypt-proxy was luci? I google for a long time, I did not find the relevant page.

**Comment by q158073378252010** [comment]
@black-roland  You can talk about how to write dnscrypt-proxy was luci? I google for a long time, I did not find the relevant page.

**Comment by black-roland** [comment]
@q158073378252010 you can find example in OpenWrt packages. For example: https://github.com/tohojo/sqm-scripts/tree/master/luci and https://github.com/openwrt/luci/tree/master/applications/luci-app-ddns

**Comment by q158073378252010** [comment]
@black-roland  How are you done? ”OpenWrt-SDK-15.05.1-ar71xx-generic“ Compile Error, system：Debian GNU/Linux 8.5
error:
checking for mips-openwrt-linux-gcc... ccache_cc
checking whether the C compiler works... no
configure: error: in `/home/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/libsodium-1.0.11':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:55: recipe for target '/home/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/libsodium-1.0.11/.configured_yyn' failed
make[3]: *** [/home/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/libsodium-1.0.11/.configured_yyn] Error 77
make[3]: Leaving directory '/home/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/package/exOpenWrt/package/libsodium'
package/Makefile:191: recipe for target 'package/exOpenWrt/package/libsodium/compile' failed
make[2]: *** [package/exOpenWrt/package/libsodium/compile] Error 2
make[2]: Leaving directory '/home/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'
package/Makefile:188: recipe for target '/home/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: *** [/home/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/OpenWrt-SDK-15.05.1-ar71xx-generic
