### ISSUE TITLE
user.err : dnscrypt-proxy Support for plugins hasn't been compiled in

### ISSUE THREAD

**Issue by ghost** [black-roland/exOpenWrt#22]
Gonna close this. Noticed that lede is using 1.9, so is up to date now. If you read this I would love to see a dnscrypt-proxy-full package though in the meantime will work towards building one for myself. So to use the different features/plugins.

Thanks again for your work

**Comment by wcat13** [comment]
Gonna close this. Noticed that lede is using 1.9, so is up to date now. If you read this I would love to see a dnscrypt-proxy-full package though in the meantime will work towards building one for myself. So to use the different features/plugins.

Thanks again for your work

**Comment by black-roland** [comment]
Dnscrypt from this repository merged to mainstream, so please open issues [here](https://github.com/openwrt/packages/issues). This repository now just for old OpenWrt versions.

About plugins please see [this discussion](https://github.com/openwrt/packages/pull/3103#r77167846). Which plugins do you want to use? Can it be replaced with built-in dnsmasq?
