### ISSUE TITLE
Autostart not working

### ISSUE THREAD

**Issue by Yaze** [black-roland/exOpenWrt#7]
Hello there, I have weird problem.
I'm using this opkg source:
src/gz exopenwrt http://exopenwrt.and.in.net/barrier_breaker/ar71xx/packages/exOpenWrt
and: BB (14.07, r42625)

The problem is that dnscrypt-proxy is not starting up (after enabling in init), I can run it manually by /etc/init.d/dnscrypt-proxy start, but enable is not working..

Any clue?

**Comment by black-roland** [comment]
Work like a charm with procd (since 1.6.0-2).
